title: hodler webdev tutorials
author: bhodler
email: bhodler@yandex.com
description: > # this means to ignore newlines until "baseurl:"
  Dedicated to teaching beginner the "a to z" of web development

# social links
twitter_username: nil
github_username:  bhodler

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
